from __future__ import annotations

from macrodata.core.models import SourceCatalogEntry


def _fred(dataset: str, name: str, description: str, unit: str | None, frequency: str | None) -> SourceCatalogEntry:
    return SourceCatalogEntry(
        series_key=f"fred:{dataset}",
        name=name,
        provider="fred",
        dataset=dataset,
        description=description,
        unit=unit,
        frequency=frequency,
        latency_class="eod",
        requires_api_key=False,
        source_url=f"https://fred.stlouisfed.org/series/{dataset}",
        license_note=(
            "FRED terms and upstream source terms apply; "
            "API key is optional because the public CSV endpoint is supported."
        ),
    )


def _yahoo(symbol: str, name: str, description: str) -> SourceCatalogEntry:
    return SourceCatalogEntry(
        series_key=f"yahoo:{symbol}",
        name=name,
        provider="yahoo",
        dataset=symbol,
        description=description,
        unit="price",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url=f"https://finance.yahoo.com/quote/{symbol}",
        license_note=(
            "Yahoo Finance data is accessed through yfinance, an unofficial library not affiliated with Yahoo; "
            "Yahoo API usage is intended for personal use."
        ),
    )


def _cftc(dataset: str, name: str, description: str) -> SourceCatalogEntry:
    return SourceCatalogEntry(
        series_key=f"cftc:{dataset}",
        name=name,
        provider="cftc",
        dataset=dataset,
        description=description,
        unit="contracts",
        frequency="weekly",
        latency_class="weekly",
        requires_api_key=False,
        source_url="https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
        license_note="CFTC public data terms apply.",
    )


CATALOG_ENTRIES: list[SourceCatalogEntry] = [
    _fred("DFF", "Effective Federal Funds Rate", "Daily effective federal funds rate.", "percent", "daily"),
    _fred("FEDFUNDS", "Federal Funds Effective Rate", "Monthly effective federal funds rate.", "percent", "monthly"),
    _fred("DGS1MO", "1-Month Treasury Constant Maturity Rate", "US 1-month Treasury yield.", "percent", "daily"),
    _fred("DGS3MO", "3-Month Treasury Constant Maturity Rate", "US 3-month Treasury yield.", "percent", "daily"),
    _fred("DGS6MO", "6-Month Treasury Constant Maturity Rate", "US 6-month Treasury yield.", "percent", "daily"),
    _fred("DGS1", "1-Year Treasury Constant Maturity Rate", "US 1-year Treasury yield.", "percent", "daily"),
    _fred("DGS2", "2-Year Treasury Constant Maturity Rate", "US 2-year Treasury yield.", "percent", "daily"),
    _fred("DGS3", "3-Year Treasury Constant Maturity Rate", "US 3-year Treasury yield.", "percent", "daily"),
    _fred("DGS5", "5-Year Treasury Constant Maturity Rate", "US 5-year Treasury yield.", "percent", "daily"),
    _fred("DGS7", "7-Year Treasury Constant Maturity Rate", "US 7-year Treasury yield.", "percent", "daily"),
    _fred("DGS10", "10-Year Treasury Constant Maturity Rate", "US 10-year Treasury yield.", "percent", "daily"),
    _fred("DGS20", "20-Year Treasury Constant Maturity Rate", "US 20-year Treasury yield.", "percent", "daily"),
    _fred("DGS30", "30-Year Treasury Constant Maturity Rate", "US 30-year Treasury yield.", "percent", "daily"),
    _fred("T10Y2Y", "10-Year Minus 2-Year Treasury Spread", "Treasury curve slope.", "percent", "daily"),
    _fred(
        "T10Y3M",
        "10-Year Minus 3-Month Treasury Spread",
        "Treasury recession-risk curve slope.",
        "percent",
        "daily",
    ),
    _fred("DFII5", "5-Year Treasury Inflation-Indexed Security", "US 5-year real yield.", "percent", "daily"),
    _fred("DFII10", "10-Year Treasury Inflation-Indexed Security", "US 10-year real yield.", "percent", "daily"),
    _fred("DFII30", "30-Year Treasury Inflation-Indexed Security", "US 30-year real yield.", "percent", "daily"),
    _fred(
        "T5YIE", "5-Year Breakeven Inflation Rate", "Market implied 5-year inflation compensation.", "percent", "daily"
    ),
    _fred("T10YIE", "10-Year Breakeven Inflation Rate", "Market implied inflation compensation.", "percent", "daily"),
    _fred(
        "T5YIFR",
        "5-Year, 5-Year Forward Inflation Expectation Rate",
        "Forward inflation expectation proxy.",
        "percent",
        "daily",
    ),
    _fred(
        "MICH",
        "University of Michigan Inflation Expectation",
        "Survey-based one-year consumer inflation expectation proxy.",
        "percent",
        "monthly",
    ),
    _fred("DFEDTARU", "Federal Funds Target Range Upper Limit", "Fed target range upper bound.", "percent", "daily"),
    _fred("DFEDTARL", "Federal Funds Target Range Lower Limit", "Fed target range lower bound.", "percent", "daily"),
    _fred("EFFR", "Effective Federal Funds Rate", "Effective overnight federal funds rate.", "percent", "daily"),
    _fred(
        "SOFR30DAYAVG",
        "30-Day Average SOFR",
        "30-day average secured overnight financing rate.",
        "percent",
        "daily",
    ),
    _fred("IORB", "Interest Rate on Reserve Balances", "Fed administered reserve rate.", "percent", "daily"),
    _fred("WALCL", "Fed Total Assets", "Federal Reserve balance sheet total assets.", "millions_usd", "weekly"),
    _fred("WRBWFRBL", "Reserve Balances", "Reserve balances with Federal Reserve Banks.", "millions_usd", "weekly"),
    _fred("RRPONTSYD", "Overnight Reverse Repo", "Overnight reverse repurchase agreements.", "billions_usd", "daily"),
    _fred("GDP", "Gross Domestic Product", "Nominal US gross domestic product.", "billions_usd", "quarterly"),
    _fred(
        "GDPC1", "Real Gross Domestic Product", "Real US gross domestic product.", "billions_chained_usd", "quarterly"
    ),
    _fred("GDPDEF", "GDP Deflator", "US GDP implicit price deflator.", "index", "quarterly"),
    _fred("PAYEMS", "All Employees, Total Nonfarm", "US nonfarm payroll employment.", "thousands_persons", "monthly"),
    _fred("UNRATE", "Unemployment Rate", "US civilian unemployment rate.", "percent", "monthly"),
    _fred("CIVPART", "Labor Force Participation Rate", "US labor force participation rate.", "percent", "monthly"),
    _fred("ICSA", "Initial Claims", "US weekly initial unemployment insurance claims.", "number", "weekly"),
    _fred("JTSJOL", "Job Openings: Total Nonfarm", "US nonfarm job openings.", "thousands", "monthly"),
    _fred("CPIAUCSL", "Consumer Price Index", "US headline CPI for all urban consumers.", "index", "monthly"),
    _fred("CPILFESL", "Core Consumer Price Index", "US CPI excluding food and energy.", "index", "monthly"),
    _fred("PPIACO", "Producer Price Index", "US producer price index for all commodities.", "index", "monthly"),
    _fred("PCEPI", "Personal Consumption Expenditures Price Index", "US headline PCE price index.", "index", "monthly"),
    _fred("PCEPILFE", "Core PCE Price Index", "US PCE price index excluding food and energy.", "index", "monthly"),
    _fred(
        "PCE",
        "Personal Consumption Expenditures",
        "US nominal personal consumption expenditures.",
        "billions_usd",
        "monthly",
    ),
    _fred(
        "PCEC96",
        "Real Personal Consumption Expenditures",
        "US real personal consumption expenditures.",
        "billions_chained_usd",
        "monthly",
    ),
    _fred("RSAFS", "Advance Retail Sales", "US advance retail and food services sales.", "millions_usd", "monthly"),
    _fred("INDPRO", "Industrial Production Index", "US industrial production index.", "index", "monthly"),
    _fred("HOUST", "Housing Starts", "US new privately-owned housing units started.", "thousands_units", "monthly"),
    _fred(
        "UMCSENT",
        "University of Michigan Consumer Sentiment",
        "US consumer sentiment survey index.",
        "index",
        "monthly",
    ),
    _fred(
        "PSAVERT",
        "Personal Saving Rate",
        "US personal saving as a percentage of disposable income.",
        "percent",
        "monthly",
    ),
    _fred("BAMLC0A0CM", "ICE BofA US Corporate OAS", "Investment-grade corporate OAS proxy.", "percent", "daily"),
    _fred("BAMLC0A1CAAA", "ICE BofA AAA US Corporate OAS", "AAA corporate credit OAS proxy.", "percent", "daily"),
    _fred("BAMLC0A2CAA", "ICE BofA AA US Corporate OAS", "AA corporate credit OAS proxy.", "percent", "daily"),
    _fred("BAMLC0A3CA", "ICE BofA A US Corporate OAS", "A corporate credit OAS proxy.", "percent", "daily"),
    _fred("BAMLC0A4CBBB", "ICE BofA BBB US Corporate OAS", "BBB corporate credit OAS proxy.", "percent", "daily"),
    _fred("BAMLH0A0HYM2", "ICE BofA US High Yield OAS", "High-yield OAS proxy.", "percent", "daily"),
    _fred("BAMLH0A1HYBB", "ICE BofA BB US High Yield OAS", "BB high-yield credit OAS proxy.", "percent", "daily"),
    _fred("BAMLH0A2HYB", "ICE BofA B US High Yield OAS", "B high-yield credit OAS proxy.", "percent", "daily"),
    _fred(
        "BAMLH0A3HYC",
        "ICE BofA CCC & Lower US High Yield OAS",
        "CCC and lower high-yield OAS proxy.",
        "percent",
        "daily",
    ),
    _fred(
        "BAMLC0A0CMEY",
        "ICE BofA US Corporate Effective Yield",
        "Investment-grade corporate yield proxy.",
        "percent",
        "daily",
    ),
    _fred(
        "BAMLH0A0HYM2EY",
        "ICE BofA US High Yield Effective Yield",
        "High-yield corporate yield proxy.",
        "percent",
        "daily",
    ),
    _fred("STLFSI4", "St. Louis Fed Financial Stress Index", "Broad US financial stress proxy.", "index", "weekly"),
    _fred(
        "NFCI",
        "Chicago Fed National Financial Conditions Index",
        "US financial conditions stress proxy.",
        "index",
        "weekly",
    ),
    _fred(
        "ANFCI",
        "Chicago Fed Adjusted National Financial Conditions Index",
        "Adjusted US financial conditions proxy.",
        "index",
        "weekly",
    ),
    _fred("VIXCLS", "CBOE VIX Close", "Equity volatility proxy.", "index", "daily"),
    _fred(
        "VXVCLS",
        "CBOE S&P 500 3-Month Volatility Index",
        "Three-month VIX proxy for public volatility term structure monitoring.",
        "index",
        "daily",
    ),
    _fred("VXNCLS", "CBOE NASDAQ 100 Volatility Index", "Nasdaq 100 implied volatility proxy.", "index", "daily"),
    _fred("RVXCLS", "CBOE Russell 2000 Volatility Index", "Russell 2000 implied volatility proxy.", "index", "daily"),
    _fred("GVZCLS", "CBOE Gold ETF Volatility Index", "Gold ETF implied volatility proxy.", "index", "daily"),
    _fred("OVXCLS", "CBOE Crude Oil ETF Volatility Index", "Crude oil ETF implied volatility proxy.", "index", "daily"),
    _fred("EVZCLS", "CBOE EuroCurrency Volatility Index", "Euro currency implied volatility proxy.", "index", "daily"),
    _fred("SP500", "S&P 500 Index", "US large-cap equity index level.", "index", "daily"),
    _fred("NASDAQCOM", "NASDAQ Composite Index", "US Nasdaq Composite index level.", "index", "daily"),
    _fred(
        "DCOILWTICO",
        "WTI Crude Oil Price",
        "West Texas Intermediate crude oil spot price.",
        "usd_per_barrel",
        "daily",
    ),
    _fred(
        "DCOILBRENTEU",
        "Brent Crude Oil Price",
        "Brent crude oil spot price.",
        "usd_per_barrel",
        "daily",
    ),
    _fred("DHHNGSP", "Henry Hub Natural Gas Spot Price", "US natural gas spot price.", "usd_per_mmbtu", "daily"),
    _fred(
        "DTWEXBGS",
        "Nominal Broad US Dollar Index",
        "Trade-weighted US dollar broad goods and services index.",
        "index",
        "daily",
    ),
    _fred("DEXUSEU", "US / Euro Foreign Exchange Rate", "US dollar to euro exchange rate.", "usd_per_eur", "daily"),
    _fred(
        "DEXJPUS",
        "Japan / US Foreign Exchange Rate",
        "Japanese yen to US dollar exchange rate.",
        "jpy_per_usd",
        "daily",
    ),
    _fred(
        "DEXCHUS",
        "China / US Foreign Exchange Rate",
        "Chinese yuan to US dollar exchange rate.",
        "cny_per_usd",
        "daily",
    ),
    _fred(
        "DEXUSUK", "US / UK Foreign Exchange Rate", "US dollar to British pound exchange rate.", "usd_per_gbp", "daily"
    ),
    _yahoo("^GSPC", "S&P 500 Index", "S&P 500 index level from Yahoo Finance."),
    _yahoo("^NDX", "Nasdaq 100 Index", "Nasdaq 100 index level from Yahoo Finance."),
    _yahoo("^DJI", "Dow Jones Industrial Average", "Dow Jones Industrial Average index level from Yahoo Finance."),
    _yahoo("^RUT", "Russell 2000 Index", "Russell 2000 index level from Yahoo Finance."),
    _yahoo("SPY", "SPDR S&P 500 ETF Trust", "S&P 500 ETF price proxy."),
    _yahoo("QQQ", "Invesco QQQ Trust", "Nasdaq 100 ETF price proxy."),
    _yahoo("DIA", "SPDR Dow Jones Industrial Average ETF Trust", "Dow Jones Industrial Average ETF price proxy."),
    _yahoo("IWM", "iShares Russell 2000 ETF", "US small-cap ETF price proxy."),
    _yahoo("EFA", "iShares MSCI EAFE ETF", "Developed ex-US equity ETF price proxy."),
    _yahoo("EEM", "iShares MSCI Emerging Markets ETF", "Emerging-market equity ETF price proxy."),
    _yahoo("TLT", "iShares 20+ Year Treasury Bond ETF", "Long-duration Treasury ETF price proxy."),
    _yahoo("IEF", "iShares 7-10 Year Treasury Bond ETF", "Intermediate Treasury ETF price proxy."),
    _yahoo("SHY", "iShares 1-3 Year Treasury Bond ETF", "Short-duration Treasury ETF price proxy."),
    _yahoo("TIP", "iShares TIPS Bond ETF", "Inflation-linked Treasury ETF price proxy."),
    _yahoo("BND", "Vanguard Total Bond Market ETF", "Broad US bond market ETF price proxy."),
    _yahoo("HYG", "iShares iBoxx High Yield Corporate Bond ETF", "High-yield credit ETF price proxy."),
    _yahoo("JNK", "SPDR Bloomberg High Yield Bond ETF", "High-yield credit ETF price proxy."),
    _yahoo("LQD", "iShares iBoxx Investment Grade Corporate Bond ETF", "Investment-grade credit ETF price proxy."),
    _yahoo("GLD", "SPDR Gold Shares", "Gold ETF price proxy."),
    _yahoo("SLV", "iShares Silver Trust", "Silver ETF price proxy."),
    _yahoo("GC=F", "Gold Futures", "COMEX gold futures price proxy."),
    _yahoo("SI=F", "Silver Futures", "COMEX silver futures price proxy."),
    _yahoo("USO", "United States Oil Fund", "Oil ETF price proxy."),
    _yahoo("CL=F", "WTI Crude Oil Futures", "NYMEX WTI crude oil futures price proxy."),
    _yahoo("UNG", "United States Natural Gas Fund", "Natural gas ETF price proxy."),
    _yahoo("NG=F", "Natural Gas Futures", "NYMEX natural gas futures price proxy."),
    _yahoo("CPER", "United States Copper Index Fund", "Copper ETF price proxy."),
    _yahoo("HG=F", "Copper Futures", "COMEX copper futures price proxy."),
    _yahoo("SMH", "VanEck Semiconductor ETF", "Semiconductor equity ETF price proxy."),
    _yahoo("SOXX", "iShares Semiconductor ETF", "Semiconductor equity ETF price proxy."),
    _yahoo("UUP", "Invesco DB US Dollar Index Bullish Fund", "US dollar ETF price proxy."),
    _yahoo("FXE", "Invesco CurrencyShares Euro Trust", "Euro ETF price proxy."),
    _yahoo("FXY", "Invesco CurrencyShares Japanese Yen Trust", "Japanese yen ETF price proxy."),
    _yahoo("DX-Y.NYB", "US Dollar Index", "US Dollar Index price proxy."),
    _yahoo("EURUSD=X", "EUR/USD", "Euro to US dollar spot FX proxy."),
    _yahoo("GBPUSD=X", "GBP/USD", "British pound to US dollar spot FX proxy."),
    _yahoo("USDJPY=X", "USD/JPY", "US dollar to Japanese yen spot FX proxy."),
    _yahoo("USDCNY=X", "USD/CNY", "US dollar to Chinese yuan spot FX proxy."),
    _yahoo("USDKRW=X", "USD/KRW", "US dollar to Korean won spot FX proxy."),
    _yahoo("VIXY", "ProShares VIX Short-Term Futures ETF", "Short-term VIX futures ETF proxy."),
    _yahoo("BTC-USD", "Bitcoin USD", "Bitcoin spot USD price proxy."),
    _yahoo("ETH-USD", "Ether USD", "Ether spot USD price proxy."),
    _cftc(
        "financial_futures:sp500_net_noncommercial",
        "S&P 500 Net Noncommercial Positioning",
        "CFTC financial futures net noncommercial positioning for S&P 500 futures.",
    ),
    SourceCatalogEntry(
        series_key="nyfed:SOFR",
        name="Secured Overnight Financing Rate",
        provider="nyfed",
        dataset="SOFR",
        description="SOFR from NY Fed Markets API.",
        unit="percent",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rates/secured/sofr/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="nyfed:RRP",
        name="Overnight Reverse Repo Operations",
        provider="nyfed",
        dataset="RRP",
        description="NY Fed overnight reverse repo operation usage.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rp/reverserepo/propositions/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="nyfed:SRF",
        name="Standing Repo Facility Operations",
        provider="nyfed",
        dataset="SRF",
        description="NY Fed standing repo facility usage.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rp/results/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="treasury_fiscal:operating_cash_balance",
        name="Treasury Operating Cash Balance",
        provider="treasury_fiscal",
        dataset="operating_cash_balance",
        description="Treasury General Account proxy from Daily Treasury Statement.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/dts/operating_cash_balance",
        license_note="US Treasury Fiscal Data public data terms apply.",
    ),
]
