from __future__ import annotations

from macrodata.core.models import SourceCatalogEntry


def _fred(dataset: str, name: str, description: str, unit: str | None, frequency: str | None) -> SourceCatalogEntry:
    return SourceCatalogEntry(
        series_key=f"fred:{dataset}",
        name=name,
        provider="fred",
        dataset=dataset,
        description=description,
        unit=unit,
        frequency=frequency,
        latency_class="eod",
        requires_api_key=True,
        source_url=f"https://fred.stlouisfed.org/series/{dataset}",
        license_note="FRED terms and upstream source terms apply.",
    )


CATALOG_ENTRIES: list[SourceCatalogEntry] = [
    _fred("DGS2", "2-Year Treasury Constant Maturity Rate", "US 2-year Treasury yield.", "percent", "daily"),
    _fred("DGS10", "10-Year Treasury Constant Maturity Rate", "US 10-year Treasury yield.", "percent", "daily"),
    _fred("DGS30", "30-Year Treasury Constant Maturity Rate", "US 30-year Treasury yield.", "percent", "daily"),
    _fred("T10Y2Y", "10-Year Minus 2-Year Treasury Spread", "Treasury curve slope.", "percent", "daily"),
    _fred("T10YIE", "10-Year Breakeven Inflation Rate", "Market implied inflation compensation.", "percent", "daily"),
    _fred("DFEDTARU", "Federal Funds Target Range Upper Limit", "Fed target range upper bound.", "percent", "daily"),
    _fred("DFEDTARL", "Federal Funds Target Range Lower Limit", "Fed target range lower bound.", "percent", "daily"),
    _fred("IORB", "Interest Rate on Reserve Balances", "Fed administered reserve rate.", "percent", "daily"),
    _fred("WALCL", "Fed Total Assets", "Federal Reserve balance sheet total assets.", "millions_usd", "weekly"),
    _fred("WRBWFRBL", "Reserve Balances", "Reserve balances with Federal Reserve Banks.", "millions_usd", "weekly"),
    _fred("RRPONTSYD", "Overnight Reverse Repo", "Overnight reverse repurchase agreements.", "billions_usd", "daily"),
    _fred("BAMLC0A0CM", "ICE BofA US Corporate OAS", "Investment-grade corporate OAS proxy.", "percent", "daily"),
    _fred("BAMLH0A0HYM2", "ICE BofA US High Yield OAS", "High-yield OAS proxy.", "percent", "daily"),
    _fred("VIXCLS", "CBOE VIX Close", "Equity volatility proxy.", "index", "daily"),
    SourceCatalogEntry(
        series_key="nyfed:SOFR",
        name="Secured Overnight Financing Rate",
        provider="nyfed",
        dataset="SOFR",
        description="SOFR from NY Fed Markets API.",
        unit="percent",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rates/secured/sofr/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="nyfed:RRP",
        name="Overnight Reverse Repo Operations",
        provider="nyfed",
        dataset="RRP",
        description="NY Fed overnight reverse repo operation usage.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rp/reverserepo/propositions/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="nyfed:SRF",
        name="Standing Repo Facility Operations",
        provider="nyfed",
        dataset="SRF",
        description="NY Fed standing repo facility usage.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://markets.newyorkfed.org/api/rp/srf/propositions/search.json",
        license_note="NY Fed public data terms apply.",
    ),
    SourceCatalogEntry(
        series_key="treasury_fiscal:operating_cash_balance",
        name="Treasury Operating Cash Balance",
        provider="treasury_fiscal",
        dataset="operating_cash_balance",
        description="Treasury General Account proxy from Daily Treasury Statement.",
        unit="millions_usd",
        frequency="daily",
        latency_class="daily",
        requires_api_key=False,
        source_url="https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/dts/operating_cash_balance",
        license_note="US Treasury Fiscal Data public data terms apply.",
    ),
]
